x-restart-policy: &restart_policy
  restart: unless-stopped
x-sentry-defaults: &sentry_defaults
  <<: *restart_policy
  image: sentry-self-hosted-local
  # Set the platform to build for linux/arm64 when needed on Apple silicon Macs.
  platform: ${DOCKER_PLATFORM:-}
  build:
    context: ./sentry
    args:
      - SENTRY_IMAGE
  # external_links:
  #   - kafka
  #   - snuba-consumer
  #   - snuba-outcomes-consumer
  #   - snuba-sessions-consumer
  #   - snuba-transactions-consumer
  #   - snuba-subscription-consumer-events
  #   - snuba-subscription-consumer-transactions
  #   - snuba-replacer
  #   - redis
  #   - memcached
  #   - smtp
  #   - snuba-api
  #   - symbolicator
  #   - vroom
  entrypoint: "/etc/sentry/entrypoint.sh"
  command: ["run", "web"]
  environment:
    PYTHONUSERBASE: "/data/custom-packages"
    SENTRY_CONF: "/etc/sentry"
    SNUBA: "$SENTRY_MAIN_ENDPOINT:1218"
    VROOM: "$SENTRY_MAIN_ENDPOINT:8085"
    # Force everything to use the system CA bundle
    # This is mostly needed to support installing custom CA certs
    # This one is used by botocore
    DEFAULT_CA_BUNDLE: &ca_bundle "/etc/ssl/certs/ca-certificates.crt"
    # This one is used by requests
    REQUESTS_CA_BUNDLE: *ca_bundle
    # This one is used by grpc/google modules
    GRPC_DEFAULT_SSL_ROOTS_FILE_PATH_ENV_VAR: *ca_bundle
    # Leaving the value empty to just pass whatever is set
    # on the host system (or in the .env file)
    SENTRY_EVENT_RETENTION_DAYS:
    SENTRY_MAIL_HOST:
    SENTRY_MAX_EXTERNAL_SOURCEMAP_SIZE:
    # Set this value if you plan on using the Suggested Fix Feature
    OPENAI_API_KEY:
    RABBITMQ_HOST: "$RABBITMQ_HOST"
    RABBITMQ_USERNAME: "$RABBITMQ_USERNAME"
    RABBITMQ_PASSWORD: "$RABBITMQ_PASSWORD"
    POSTGRESQL_DB_NAME: "$POSTGRESQL_DB_NAME"
    POSTGRESQL_USER: "$POSTGRESQL_USER"
    POSTGRESQL_PASSWORD: "$POSTGRESQL_PASSWORD"
    POSTGRESQL_HOST: "$POSTGRESQL_HOST"
    SENTRY_MAIN_ENDPOINT: "$SENTRY_MAIN_ENDPOINT"
    SENTRY_STORAGE_ENDPOINT: "$SENTRY_STORAGE_ENDPOINT"
  volumes:
    - "sentry-data:/data"
    - "./sentry:/etc/sentry"
    - "./geoip:/geoip:ro"
    - "./certificates:/usr/local/share/ca-certificates:ro"
services:
  events-consumer:
    <<: *sentry_defaults
    command: run consumer ingest-events --consumer-group ingest-consumer
  attachments-consumer:
    <<: *sentry_defaults
    command: run consumer ingest-attachments --consumer-group ingest-consumer
  transactions-consumer:
    <<: *sentry_defaults
    command: run consumer ingest-transactions --consumer-group ingest-consumer
    deploy:
      replicas: 15
  metrics-consumer:
    <<: *sentry_defaults
    command: run consumer ingest-metrics --consumer-group metrics-consumer
  generic-metrics-consumer:
    <<: *sentry_defaults
    command: run consumer ingest-generic-metrics --consumer-group generic-metrics-consumer
    deploy:
      replicas: 6
  # billing-metrics-consumer:
  #   <<: *sentry_defaults
  #   command: run consumer billing-metrics-consumer --consumer-group billing-metrics-consumer
  # ingest-replay-recordings:
  #   <<: *sentry_defaults
  #   command: run consumer ingest-replay-recordings --consumer-group ingest-replay-recordings
  ingest-occurrences:
    <<: *sentry_defaults
    command: run consumer ingest-occurrences --consumer-group ingest-occurrences
  ingest-profiles:
    <<: *sentry_defaults
    command: run consumer --no-strict-offset-reset ingest-profiles --consumer-group ingest-profiles
  post-process-forwarder-errors:
    <<: *sentry_defaults
    command: run consumer post-process-forwarder-errors --consumer-group post-process-forwarder --synchronize-commit-log-topic=snuba-commit-log --synchronize-commit-group=snuba-consumers
    deploy:
      replicas: 3
  post-process-forwarder-transactions:
    <<: *sentry_defaults
    command: run consumer post-process-forwarder-transactions --consumer-group post-process-forwarder --synchronize-commit-log-topic=snuba-transactions-commit-log --synchronize-commit-group transactions_group
    deploy:
      replicas: 8
  post-process-forwarder-issue-platform:
    <<: *sentry_defaults
    command: run consumer post-process-forwarder-issue-platform --consumer-group post-process-forwarder --synchronize-commit-log-topic=snuba-generic-events-commit-log --synchronize-commit-group generic_events_group
  subscription-consumer-events:
    <<: *sentry_defaults
    command: run consumer events-subscription-results --consumer-group query-subscription-consumer
  subscription-consumer-transactions:
    <<: *sentry_defaults
    command: run consumer transactions-subscription-results --consumer-group query-subscription-consumer
  subscription-consumer-metrics:
    <<: *sentry_defaults
    command: run consumer metrics-subscription-results --consumer-group query-subscription-consumer
  subscription-consumer-generic-metrics:
    <<: *sentry_defaults
    command: run consumer generic-metrics-subscription-results --consumer-group query-subscription-consumer
volumes:
  # These store application data that should persist across restarts.
  sentry-data:
    external: true