x-restart-policy: &restart_policy
  restart: unless-stopped
x-depends_on-healthy: &depends_on-healthy
  condition: service_healthy
x-depends_on-default: &depends_on-default
  condition: service_started
x-healthcheck-defaults: &healthcheck_defaults
  # Avoid setting the interval too small, as docker uses much more CPU than one would expect.
  # Related issues:
  # https://github.com/moby/moby/issues/39102
  # https://github.com/moby/moby/issues/39388
  # https://github.com/getsentry/self-hosted/issues/1000
  interval: "$HEALTHCHECK_INTERVAL"
  timeout: "$HEALTHCHECK_TIMEOUT"
  retries: $HEALTHCHECK_RETRIES
  start_period: 10s
x-sentry-defaults: &sentry_defaults
  <<: *restart_policy
  image: sentry-self-hosted-local
  # Set the platform to build for linux/arm64 when needed on Apple silicon Macs.
  platform: ${DOCKER_PLATFORM:-}
  build:
    context: ./sentry
    args:
      - SENTRY_IMAGE
  # external_links:
  #   - kafka
  #   - snuba-consumer
  #   - snuba-outcomes-consumer
  #   - snuba-sessions-consumer
  #   - snuba-transactions-consumer
  #   - snuba-subscription-consumer-events
  #   - snuba-subscription-consumer-transactions
  #   - snuba-replacer
  #   - redis
  #   - memcached
  #   - smtp
  #   - snuba-api
  #   - symbolicator
  #   - vroom
  entrypoint: "/etc/sentry/entrypoint.sh"
  command: ["run", "web"]
  environment:
    PYTHONUSERBASE: "/data/custom-packages"
    SENTRY_CONF: "/etc/sentry"
    SNUBA: "$SENTRY_MAIN_ENDPOINT:1218"
    VROOM: "$SENTRY_MAIN_ENDPOINT:8085"
    # Force everything to use the system CA bundle
    # This is mostly needed to support installing custom CA certs
    # This one is used by botocore
    DEFAULT_CA_BUNDLE: &ca_bundle "/etc/ssl/certs/ca-certificates.crt"
    # This one is used by requests
    REQUESTS_CA_BUNDLE: *ca_bundle
    # This one is used by grpc/google modules
    GRPC_DEFAULT_SSL_ROOTS_FILE_PATH_ENV_VAR: *ca_bundle
    # Leaving the value empty to just pass whatever is set
    # on the host system (or in the .env file)
    SENTRY_EVENT_RETENTION_DAYS:
    SENTRY_MAIL_HOST:
    SENTRY_MAX_EXTERNAL_SOURCEMAP_SIZE:
    # Set this value if you plan on using the Suggested Fix Feature
    OPENAI_API_KEY:
    RABBITMQ_HOST: "$RABBITMQ_HOST"
    RABBITMQ_USERNAME: "$RABBITMQ_USERNAME"
    RABBITMQ_PASSWORD: "$RABBITMQ_PASSWORD"
    POSTGRESQL_DB_NAME: "$POSTGRESQL_DB_NAME"
    POSTGRESQL_USER: "$POSTGRESQL_USER"
    POSTGRESQL_PASSWORD: "$POSTGRESQL_PASSWORD"
    POSTGRESQL_HOST: "$POSTGRESQL_HOST"
    SENTRY_MAIN_ENDPOINT: "$SENTRY_MAIN_ENDPOINT"
  volumes:
    - "sentry-data:/data"
    - "./sentry:/etc/sentry"
    - "./geoip:/geoip:ro"
    - "./certificates:/usr/local/share/ca-certificates:ro"
services:
  worker:
    <<: *sentry_defaults
    command: run worker
    deploy:
      replicas: 3
  save-event-transaction-worker:
    <<: *sentry_defaults
    command: run worker -Q events.save_event_transaction
    deploy:
      replicas: 12
  post-process--transactions-worker:
    <<: *sentry_defaults
    command: run worker -Q post_process_transactions
    deploy:
      replicas: 4
volumes:
  # These store application data that should persist across restarts.
  sentry-data:
    external: true
