relay:
  upstream: "http://web:9001/"
  host: 0.0.0.0
  port: 3000
logging:
  level: WARN
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "10.0.31.224:9091"}
    - {name: "message.max.bytes", value: 50000000} # 50MB
  redis: redis://10.0.31.224:6379
  geoip_path: "/geoip/GeoLite2-City.mmdb"
