relay:
  upstream: "http://web:9000/"
  host: 0.0.0.0
  port: 3000
logging:
  level: WARN
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "kafka:9092"}
    - {name: "message.max.bytes", value: 250000000} # 50MB
  redis: redis://redis:6379
  geoip_path: "/geoip/GeoLite2-City.mmdb"
limits:
  max_envelope_size: 250000000
  max_concurrent_queries: 50
  max_concurrent_requests: 10000
cache:
  envelope_buffer_size: 7500
spool:
  envelopes:
    path: /var/tmp/sentry_relay_spool
    max_memory_size: 2GB
    max_disk_size: 75GB
