relay:
  upstream: "http://web:9000/"
  host: 0.0.0.0
  port: 3000
logging:
  level: WARN
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "https://sentry.typeset.io:9092"}
    - {name: "message.max.bytes", value: 50000000} # 50MB
  redis: https://sentry.typeset.io:6379
  geoip_path: "/geoip/GeoLite2-City.mmdb"
